export default [
    {
        "id": 12314,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Slvg & O-O Progrmng-Honor",
        "academic_period": 201710,
        "academic_period_desc": "Fall 2016",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Dunsmore, Hubert E.",
        "a": "100.0%",
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12315,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Slvng & O-O Progrm-Honor",
        "academic_period": 201820,
        "academic_period_desc": "Spring 2018",
        "section": "LE1",
        "crn": 19979,
        "instructor": "Dunsmore, Hubert E.",
        "a": null,
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": "100.0%",
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12316,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Slvng & O-O Progrmg-Honor",
        "academic_period": 201820,
        "academic_period_desc": "Spring 2018",
        "section": "LE1",
        "crn": 19979,
        "instructor": "Dunsmore, Hubert E.",
        "a": "100.0%",
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12317,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Prog-Honors",
        "academic_period": 201720,
        "academic_period_desc": "Spring 2017",
        "section": "LE1",
        "crn": 19979,
        "instructor": "Dunsmore, Hubert E.",
        "a": "100.0%",
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12318,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Prog-Honors",
        "academic_period": 202020,
        "academic_period_desc": "Spring 2020",
        "section": "LE2",
        "crn": 11064,
        "instructor": "Dunsmore, Hubert E.",
        "a": "50.0%",
        "a_minus": null,
        "a_plus": "50.0%",
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12319,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201630,
        "academic_period_desc": "Summer 2016",
        "section": "LE1",
        "crn": 22937,
        "instructor": "Dunsmore, Hubert E.",
        "a": "37.8%",
        "a_minus": "2.2%",
        "a_plus": null,
        "au": null,
        "b": "31.1%",
        "b_minus": "8.9%",
        "b_plus": null,
        "c": "4.4%",
        "c_minus": "2.2%",
        "c_plus": null,
        "d": "2.2%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "4.4%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "6.7%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12320,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201710,
        "academic_period_desc": "Fall 2016",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Dunsmore, Hubert E.",
        "a": "65.6%",
        "a_minus": "5.4%",
        "a_plus": "0.4%",
        "au": null,
        "b": "12.9%",
        "b_minus": "1.3%",
        "b_plus": "2.2%",
        "c": "5.4%",
        "c_minus": "0.4%",
        "c_plus": "0.4%",
        "d": "1.8%",
        "d_minus": "0.9%",
        "d_plus": "0.9%",
        "e": null,
        "f": "2.2%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12321,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201710,
        "academic_period_desc": "Fall 2016",
        "section": "GLD",
        "crn": 34295,
        "instructor": "Prabhakar, Sunil K.",
        "a": "34.5%",
        "a_minus": "7.7%",
        "a_plus": null,
        "au": null,
        "b": "21.1%",
        "b_minus": "6.7%",
        "b_plus": "5.2%",
        "c": "11.3%",
        "c_minus": "1.0%",
        "c_plus": "0.5%",
        "d": "4.6%",
        "d_minus": "1.0%",
        "d_plus": null,
        "e": null,
        "f": "5.7%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "0.5%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12322,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201720,
        "academic_period_desc": "Spring 2017",
        "section": "LE1",
        "crn": 19979,
        "instructor": "Dunsmore, Hubert E.",
        "a": "27.5%",
        "a_minus": "10.4%",
        "a_plus": null,
        "au": null,
        "b": "23.5%",
        "b_minus": "6.9%",
        "b_plus": "4.0%",
        "c": "7.4%",
        "c_minus": "0.7%",
        "c_plus": "1.7%",
        "d": "4.5%",
        "d_minus": "0.5%",
        "d_plus": "0.7%",
        "e": null,
        "f": "6.2%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": "0.7%",
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "5.2%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12323,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201730,
        "academic_period_desc": "Summer 2017",
        "section": "LE1",
        "crn": 22937,
        "instructor": "Dunsmore, Hubert E.",
        "a": "18.9%",
        "a_minus": "7.5%",
        "a_plus": null,
        "au": null,
        "b": "22.6%",
        "b_minus": "5.7%",
        "b_plus": "1.9%",
        "c": "20.8%",
        "c_minus": null,
        "c_plus": "3.8%",
        "d": "7.5%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "5.7%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "5.7%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12324,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201810,
        "academic_period_desc": "Fall 2017",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Turkstra, Jeffrey A.",
        "a": "55.7%",
        "a_minus": "8.6%",
        "a_plus": "0.5%",
        "au": null,
        "b": "16.2%",
        "b_minus": "0.5%",
        "b_plus": "5.4%",
        "c": "2.2%",
        "c_minus": "3.2%",
        "c_plus": "0.5%",
        "d": "1.1%",
        "d_minus": null,
        "d_plus": "0.5%",
        "e": null,
        "f": "3.8%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "1.6%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12325,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201810,
        "academic_period_desc": "Fall 2017",
        "section": "GLD",
        "crn": 10955,
        "instructor": "Dunsmore, Hubert E.",
        "a": "35.9%",
        "a_minus": "8.8%",
        "a_plus": null,
        "au": null,
        "b": "16.0%",
        "b_minus": "3.9%",
        "b_plus": "7.2%",
        "c": "7.7%",
        "c_minus": null,
        "c_plus": "1.7%",
        "d": "2.8%",
        "d_minus": "1.7%",
        "d_plus": "0.6%",
        "e": null,
        "f": "9.9%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "3.9%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12326,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201820,
        "academic_period_desc": "Spring 2018",
        "section": "LE1",
        "crn": 19979,
        "instructor": "Dunsmore, Hubert E.",
        "a": "34.9%",
        "a_minus": "7.8%",
        "a_plus": "0.4%",
        "au": null,
        "b": "17.8%",
        "b_minus": "2.7%",
        "b_plus": "2.2%",
        "c": "8.9%",
        "c_minus": "0.9%",
        "c_plus": "2.0%",
        "d": "3.1%",
        "d_minus": "0.4%",
        "d_plus": "0.2%",
        "e": null,
        "f": "8.9%",
        "fn": null,
        "i": "0.2%",
        "i_f": null,
        "n": "0.2%",
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "9.3%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12327,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201830,
        "academic_period_desc": "Summer 2018",
        "section": "LE1",
        "crn": 22937,
        "instructor": "Dunsmore, Hubert E.",
        "a": "27.7%",
        "a_minus": "9.2%",
        "a_plus": null,
        "au": null,
        "b": "18.5%",
        "b_minus": "4.6%",
        "b_plus": "3.1%",
        "c": "9.2%",
        "c_minus": "1.5%",
        "c_plus": "1.5%",
        "d": "9.2%",
        "d_minus": "1.5%",
        "d_plus": null,
        "e": null,
        "f": "7.7%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": "1.5%",
        "ns": null,
        "p": "1.5%",
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "3.1%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12328,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201910,
        "academic_period_desc": "Fall 2018",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Turkstra, Jeffrey A.",
        "a": "63.6%",
        "a_minus": "5.1%",
        "a_plus": "1.9%",
        "au": null,
        "b": "13.6%",
        "b_minus": "2.3%",
        "b_plus": "1.4%",
        "c": "2.8%",
        "c_minus": "1.9%",
        "c_plus": "1.4%",
        "d": "2.3%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "2.3%",
        "fn": null,
        "i": "0.5%",
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "0.9%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12329,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201910,
        "academic_period_desc": "Fall 2018",
        "section": "GLD",
        "crn": 10955,
        "instructor": "Dunsmore, Hubert E.",
        "a": "31.8%",
        "a_minus": "7.1%",
        "a_plus": null,
        "au": null,
        "b": "20.9%",
        "b_minus": "2.8%",
        "b_plus": "2.8%",
        "c": "8.1%",
        "c_minus": "1.9%",
        "c_plus": "0.9%",
        "d": "4.7%",
        "d_minus": "0.5%",
        "d_plus": "0.5%",
        "e": null,
        "f": "8.5%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "9.5%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12330,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201920,
        "academic_period_desc": "Spring 2019",
        "section": "LE1",
        "crn": 19979,
        "instructor": "Dunsmore, Hubert E.",
        "a": "34.4%",
        "a_minus": "7.8%",
        "a_plus": null,
        "au": null,
        "b": "19.3%",
        "b_minus": "6.4%",
        "b_plus": "1.8%",
        "c": "10.6%",
        "c_minus": "0.9%",
        "c_plus": "1.4%",
        "d": "2.8%",
        "d_minus": "0.5%",
        "d_plus": "0.9%",
        "e": null,
        "f": "6.4%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": "0.5%",
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "6.4%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12331,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201920,
        "academic_period_desc": "Spring 2019",
        "section": "LE2",
        "crn": 11064,
        "instructor": "Bergstrom, Anthony D.",
        "a": "29.0%",
        "a_minus": "10.1%",
        "a_plus": null,
        "au": null,
        "b": "15.0%",
        "b_minus": "2.9%",
        "b_plus": "3.4%",
        "c": "11.6%",
        "c_minus": "2.9%",
        "c_plus": "3.9%",
        "d": "4.8%",
        "d_minus": "2.4%",
        "d_plus": "1.4%",
        "e": null,
        "f": "8.7%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": "0.5%",
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "3.4%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12332,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 201930,
        "academic_period_desc": "Summer 2019",
        "section": "LE1",
        "crn": 22937,
        "instructor": "Dunsmore, Hubert E.",
        "a": "32.1%",
        "a_minus": "9.5%",
        "a_plus": null,
        "au": null,
        "b": "15.5%",
        "b_minus": "4.8%",
        "b_plus": "4.8%",
        "c": "6.0%",
        "c_minus": null,
        "c_plus": "1.2%",
        "d": "2.4%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "11.9%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "11.9%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12333,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202010,
        "academic_period_desc": "Fall 2019",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Bergstrom, Anthony D.",
        "a": "64.8%",
        "a_minus": "10.0%",
        "a_plus": "0.7%",
        "au": null,
        "b": "10.3%",
        "b_minus": "1.8%",
        "b_plus": "3.6%",
        "c": "2.1%",
        "c_minus": "0.7%",
        "c_plus": "0.7%",
        "d": "0.7%",
        "d_minus": null,
        "d_plus": "0.7%",
        "e": null,
        "f": "2.1%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "1.8%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12334,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202010,
        "academic_period_desc": "Fall 2019",
        "section": "GLD",
        "crn": 10955,
        "instructor": "Dunsmore, Hubert E.",
        "a": "37.4%",
        "a_minus": "6.4%",
        "a_plus": "0.4%",
        "au": null,
        "b": "24.7%",
        "b_minus": "4.7%",
        "b_plus": "3.4%",
        "c": "11.1%",
        "c_minus": null,
        "c_plus": "3.0%",
        "d": "1.3%",
        "d_minus": "0.9%",
        "d_plus": null,
        "e": null,
        "f": "3.4%",
        "fn": null,
        "i": "0.4%",
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "3.0%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12335,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202020,
        "academic_period_desc": "Spring 2020",
        "section": "LE1",
        "crn": 19979,
        "instructor": "Bergstrom, Anthony D.",
        "a": "52.1%",
        "a_minus": "4.7%",
        "a_plus": "3.3%",
        "au": null,
        "b": "7.1%",
        "b_minus": "0.9%",
        "b_plus": "2.4%",
        "c": "1.9%",
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "1.4%",
        "fn": null,
        "i": "0.5%",
        "i_f": null,
        "n": "4.7%",
        "ns": null,
        "p": "10.9%",
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "10.0%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12336,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202020,
        "academic_period_desc": "Spring 2020",
        "section": "LE2",
        "crn": 11064,
        "instructor": "Dunsmore, Hubert E.",
        "a": "47.3%",
        "a_minus": "5.5%",
        "a_plus": "0.9%",
        "au": "0.5%",
        "b": "8.6%",
        "b_minus": "1.8%",
        "b_plus": "3.2%",
        "c": "6.4%",
        "c_minus": null,
        "c_plus": "0.5%",
        "d": "1.8%",
        "d_minus": "0.5%",
        "d_plus": null,
        "e": null,
        "f": "1.4%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": "3.2%",
        "ns": null,
        "p": "10.9%",
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "7.7%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12337,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202030,
        "academic_period_desc": "Summer 2020",
        "section": "Y01",
        "crn": 15185,
        "instructor": "Dunsmore, Hubert E.",
        "a": "32.0%",
        "a_minus": "5.2%",
        "a_plus": null,
        "au": null,
        "b": "13.4%",
        "b_minus": "6.2%",
        "b_plus": "1.0%",
        "c": "12.4%",
        "c_minus": null,
        "c_plus": null,
        "d": "4.1%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "12.4%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "13.4%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12338,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202110,
        "academic_period_desc": "Fall 2020",
        "section": "001",
        "crn": 25665,
        "instructor": "Turkstra, Jeffrey A.",
        "a": "58.7%",
        "a_minus": "8.0%",
        "a_plus": "5.3%",
        "au": null,
        "b": "8.0%",
        "b_minus": "1.3%",
        "b_plus": "2.7%",
        "c": "4.0%",
        "c_minus": null,
        "c_plus": null,
        "d": "2.7%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "5.3%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": "1.3%",
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "2.7%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12339,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202110,
        "academic_period_desc": "Fall 2020",
        "section": "002",
        "crn": 25823,
        "instructor": "Dunsmore, Hubert E.",
        "a": "48.6%",
        "a_minus": "7.3%",
        "a_plus": "1.8%",
        "au": null,
        "b": "15.6%",
        "b_minus": "1.8%",
        "b_plus": "0.9%",
        "c": "7.3%",
        "c_minus": null,
        "c_plus": "0.9%",
        "d": "2.8%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "5.5%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "7.3%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12340,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202110,
        "academic_period_desc": "Fall 2020",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Turkstra, Jeffrey A.",
        "a": "57.7%",
        "a_minus": "5.9%",
        "a_plus": "5.4%",
        "au": null,
        "b": "12.1%",
        "b_minus": "1.7%",
        "b_plus": "3.8%",
        "c": "5.0%",
        "c_minus": null,
        "c_plus": "1.7%",
        "d": "1.7%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "2.5%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "2.5%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12341,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202110,
        "academic_period_desc": "Fall 2020",
        "section": "GLD",
        "crn": 10955,
        "instructor": "Dunsmore, Hubert E.",
        "a": "38.0%",
        "a_minus": "8.4%",
        "a_plus": "0.6%",
        "au": null,
        "b": "19.0%",
        "b_minus": "3.4%",
        "b_plus": "1.7%",
        "c": "8.4%",
        "c_minus": null,
        "c_plus": "2.2%",
        "d": "0.6%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "7.8%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "10.1%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12342,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202120,
        "academic_period_desc": "Spring 2021",
        "section": "LE1",
        "crn": 28888,
        "instructor": "Dunsmore, Hubert E.",
        "a": "42.2%",
        "a_minus": "7.3%",
        "a_plus": "1.9%",
        "au": null,
        "b": "15.0%",
        "b_minus": "2.4%",
        "b_plus": "4.4%",
        "c": "4.9%",
        "c_minus": null,
        "c_plus": "0.5%",
        "d": "2.4%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "6.3%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": "0.5%",
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "12.1%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12343,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202120,
        "academic_period_desc": "Spring 2021",
        "section": "LE2",
        "crn": 28889,
        "instructor": "Dunsmore, Hubert E.",
        "a": "50.8%",
        "a_minus": "5.0%",
        "a_plus": "4.5%",
        "au": null,
        "b": "10.6%",
        "b_minus": "1.1%",
        "b_plus": "3.4%",
        "c": "9.5%",
        "c_minus": null,
        "c_plus": null,
        "d": "1.1%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "3.4%",
        "fn": null,
        "i": "0.6%",
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "10.1%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12344,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202120,
        "academic_period_desc": "Spring 2021",
        "section": "OL1",
        "crn": 26888,
        "instructor": "Dunsmore, Hubert E.",
        "a": "45.7%",
        "a_minus": "4.3%",
        "a_plus": "1.7%",
        "au": null,
        "b": "12.9%",
        "b_minus": "0.9%",
        "b_plus": "3.4%",
        "c": "7.8%",
        "c_minus": null,
        "c_plus": "0.9%",
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "9.5%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": "1.7%",
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "11.2%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12345,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202130,
        "academic_period_desc": "Summer 2021",
        "section": "L01",
        "crn": 29708,
        "instructor": "Dunsmore, Hubert E.",
        "a": "37.1%",
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": "8.6%",
        "b_minus": null,
        "b_plus": "2.9%",
        "c": "11.4%",
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "17.1%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "22.9%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12346,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202130,
        "academic_period_desc": "Summer 2021",
        "section": "Y01",
        "crn": 30773,
        "instructor": "Dunsmore, Hubert E.",
        "a": "40.0%",
        "a_minus": "6.7%",
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": "13.3%",
        "c_minus": null,
        "c_plus": "3.3%",
        "d": "6.7%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "26.7%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "3.3%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12347,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solvng & O-O Progr-Honors",
        "academic_period": 202010,
        "academic_period_desc": "Fall 2019",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Bergstrom, Anthony D.",
        "a": "100.0%",
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 12348,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solvng & O-O Progr-Honors",
        "academic_period": 202010,
        "academic_period_desc": "Fall 2019",
        "section": "GLD",
        "crn": 10955,
        "instructor": "Dunsmore, Hubert E.",
        "a": "33.3%",
        "a_minus": "33.3%",
        "a_plus": null,
        "au": null,
        "b": "33.3%",
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 46107,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solv & O-O Prgr- Honors",
        "academic_period": 202210,
        "academic_period_desc": "Fall 2021",
        "section": "GLD",
        "crn": 26043,
        "instructor": "Dunsmore, Hubert E.",
        "a": "100.0%",
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 46108,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solv & O-O Prgr-Honors",
        "academic_period": 202210,
        "academic_period_desc": "Fall 2021",
        "section": "GLD",
        "crn": 26043,
        "instructor": "Dunsmore, Hubert E.",
        "a": null,
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": "100.0%",
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 46109,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solv & O-O Progr- Honors",
        "academic_period": 202210,
        "academic_period_desc": "Fall 2021",
        "section": "GLD",
        "crn": 26043,
        "instructor": "Dunsmore, Hubert E.",
        "a": "100.0%",
        "a_minus": null,
        "a_plus": null,
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 46110,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202210,
        "academic_period_desc": "Fall 2021",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Turkstra, Jeffrey A.",
        "a": "71.4%",
        "a_minus": "4.1%",
        "a_plus": "3.8%",
        "au": null,
        "b": "7.9%",
        "b_minus": "1.0%",
        "b_plus": "0.7%",
        "c": "3.8%",
        "c_minus": null,
        "c_plus": "0.3%",
        "d": "1.0%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "4.1%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "1.7%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 46111,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202210,
        "academic_period_desc": "Fall 2021",
        "section": "GLD",
        "crn": 26043,
        "instructor": "Dunsmore, Hubert E.",
        "a": "50.3%",
        "a_minus": "7.1%",
        "a_plus": "0.7%",
        "au": null,
        "b": "13.3%",
        "b_minus": "3.1%",
        "b_plus": "2.7%",
        "c": "9.2%",
        "c_minus": null,
        "c_plus": "1.0%",
        "d": "2.0%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "7.5%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "3.1%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 50666,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202220,
        "academic_period_desc": "Spring 2022",
        "section": "LE1",
        "crn": 13105,
        "instructor": "Bergstrom, Anthony D.",
        "a": "47.7%",
        "a_minus": "4.3%",
        "a_plus": "1.2%",
        "au": null,
        "b": "10.9%",
        "b_minus": "3.5%",
        "b_plus": "2.7%",
        "c": "4.3%",
        "c_minus": null,
        "c_plus": "1.6%",
        "d": "2.7%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "9.3%",
        "fn": null,
        "i": "0.4%",
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "11.6%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 50667,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202220,
        "academic_period_desc": "Spring 2022",
        "section": "LE2",
        "crn": 13116,
        "instructor": "Dunsmore, Hubert E.",
        "a": "46.1%",
        "a_minus": "5.1%",
        "a_plus": "2.7%",
        "au": null,
        "b": "13.3%",
        "b_minus": "2.7%",
        "b_plus": "2.3%",
        "c": "9.8%",
        "c_minus": "0.4%",
        "c_plus": "0.8%",
        "d": "2.3%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "7.0%",
        "fn": null,
        "i": "0.4%",
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "7.0%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 53870,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202230,
        "academic_period_desc": "Summer 2022",
        "section": "LE1",
        "crn": 31021,
        "instructor": "Dunsmore, Hubert E.",
        "a": "36.2%",
        "a_minus": "4.3%",
        "a_plus": "1.4%",
        "au": null,
        "b": "18.8%",
        "b_minus": "5.8%",
        "b_plus": "4.3%",
        "c": "10.1%",
        "c_minus": null,
        "c_plus": "4.3%",
        "d": "1.4%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "10.1%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "2.9%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 55712,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Slvng & O-O Prgrmg-Honors",
        "academic_period": 202310,
        "academic_period_desc": "Fall 2022",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Turkstra, Jeffrey A.",
        "a": "60.0%",
        "a_minus": null,
        "a_plus": "40.0%",
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 55713,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Slvng & O-O Prgrmg-Honors",
        "academic_period": 202310,
        "academic_period_desc": "Fall 2022",
        "section": "GLD",
        "crn": 26043,
        "instructor": "Dunsmore, Hubert E.",
        "a": "66.7%",
        "a_minus": null,
        "a_plus": "33.3%",
        "au": null,
        "b": null,
        "b_minus": null,
        "b_plus": null,
        "c": null,
        "c_minus": null,
        "c_plus": null,
        "d": null,
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": null,
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": null,
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 55714,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202310,
        "academic_period_desc": "Fall 2022",
        "section": "BLK",
        "crn": 10687,
        "instructor": "Turkstra, Jeffrey A.",
        "a": "74.4%",
        "a_minus": "2.2%",
        "a_plus": "7.0%",
        "au": null,
        "b": "6.3%",
        "b_minus": "0.9%",
        "b_plus": "2.0%",
        "c": "4.7%",
        "c_minus": null,
        "c_plus": null,
        "d": "0.2%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "1.3%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "0.9%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    },
    {
        "id": 55715,
        "subject": "CS",
        "subject_desc": "CS-Computer Sciences",
        "course_num": 18000,
        "title": "Prob Solving & O-O Programming",
        "academic_period": 202310,
        "academic_period_desc": "Fall 2022",
        "section": "GLD",
        "crn": 26043,
        "instructor": "Dunsmore, Hubert E.",
        "a": "54.6%",
        "a_minus": "6.9%",
        "a_plus": "2.3%",
        "au": null,
        "b": "14.0%",
        "b_minus": "2.6%",
        "b_plus": "3.7%",
        "c": "4.6%",
        "c_minus": null,
        "c_plus": "2.3%",
        "d": "2.0%",
        "d_minus": null,
        "d_plus": null,
        "e": null,
        "f": "4.6%",
        "fn": null,
        "i": null,
        "i_f": null,
        "n": null,
        "ns": null,
        "p": null,
        "p_i": null,
        "s": null,
        "s_i": null,
        "u": null,
        "w": "2.6%",
        "w_f": null,
        "w_n": null,
        "w_u": null,
        "blank": null
    }
]