services:
  mongo:
    image: 'mongo:6.0.4'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: hunter2
    volumes:
      - mongo-data:/data/db
    networks:
      - database

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '127.0.0.1:8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: hunter2
      ME_CONFIG_MONGODB_URL: mongodb://root:hunter2@mongo:27017/
    networks:
      - database
    depends_on:
      - mongo

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - '127.0.0.1:8025:8025'
    networks:
      - database
      - email
  
  petes-plan-server:
    build: ./server
    # image: cdoner/petes-plan-server:latest
    restart: always
    ports:
      - 8000:8000
    networks:
      - database
      - email
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://root:hunter2@mongo:27017/petes-plan?authSource=admin

  petes-plan-client:
    image: cdoner/petes-plan-client:latest
    restart: always
    ports:
      - 4173:4173
    depends_on:
      - petes-plan-server

networks:
  database:
    driver: bridge
  email:
    driver: bridge

volumes:
  mongo-data: